---

- hosts: localhost
  gather_facts: False
  remote_user: user
  tasks:
    - name: Install wget
      yum:
        name: wget
        state: present
      register: output
   
    - debug:
        msg: "{{ output }}"          
        verbosity: 3
  
  

